### ISSUE TITLE
TsTool could generate `.js` + `.d.ts` files rather than `.ts`

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#160]
For later consideration...

We could have the tool's output already in JavaScript, while simultaneously emitting a corresponding `.d.ts` file that declares type information.   This would avoid making a consuming package dependent on TypeScript at build time.   Seems like a nice-to-have.

Implementation-wise in the tool, `.d.ts` files may be considered similar to the "C/C++" concept of a `.h` file.  It seems like that target is getting close to integration, so we should probably defer this.

**Comment by BurtHarris** [comment]
Low priority.

**Comment by sharwell** [comment]
I'm going to mark this as **wontfix** for now since it places the burden of type correctness entirely on the template author with no assistance from the compiler. For code as complicated as ANTLR produces, I don't think this is a maintainable solution.
