### ISSUE TITLE
antlr4ts bin script published with CRLF line endings

### ISSUE THREAD

**Issue by carlansley** [tunnelvisionlabs/antlr4ts#250]
This causes issues on MacOS/Linux etc:

```
> ./node_modules/.bin/antlr4ts 
env: node\r: No such file or directory
```

**Comment by carlansley** [comment]
Assuming `antlr4ts-cli` is being published from Windows, likely related to npm/npm#12371.

**Comment by thosakwe** [comment]
Having this error as well.

**Comment by sharwell** [comment]
@carlansley Thanks for identifying this and taking the time to file a bug. I'll get right on it!
