### ISSUE TITLE
Make parseCallStack parameter in SemanticContext.eval() optional

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#279]
I know the Java target is not clear about if [the rule stack parameter](https://github.com/tunnelvisionlabs/antlr4ts/blob/master/src/atn/SemanticContext.ts#L88) is required or not. It is simply passed on to the semantic predicate functions and might be used or not by user code.

I have the need to execute predicates without such a rule stack (simply because I don't have one in this situation) and I believe that it is rather rare that someone uses the passed in context for a predicate. And if so it would be (a documented) limitation of my implementation to not work in such a situation.

So, please make this parameter optional.

**Comment by sharwell** [comment]
💭 You can pass `ParserRuleContext.EMPTY` in this case.

**Comment by mike-lischke** [comment]
Yes, sounds like a way to solve that. So, you mean that in normal operations it can never happen an empty rule context is passed in? If so, I'm fine with your suggestion.

**Comment by sharwell** [comment]
You could get "an empty rule context" during normal parsing, but it won't be reference-equal to `ParserRuleContext.EMPTY`. You can access this value using the public static method `ParserRuleContext.emptyContext()`.

**Comment by mike-lischke** [comment]
Ok, thanks.
