### ISSUE TITLE
ATNState.serializationNames is untyped

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#282]
ATNState.serializationNames should be defined as what it is (a string array). And the member is private. Please allow public usage. Useful for debugging. Thanks.

**Comment by sharwell** [comment]
I can't find the code you are mentioning. Do you have a link to the line?

**Comment by mike-lischke** [comment]
Sorry, wrong class mentioned. It's ATNState actually.

**Comment by sharwell** [comment]
💭  I see an explicit type listed there:

https://github.com/tunnelvisionlabs/antlr4ts/blob/master/src/atn/ATNState.ts#L77

**Comment by mike-lischke** [comment]
When do you publish that :-)? And pls make the member public.

**Comment by sharwell** [comment]
That hasn't changed since the first alpha. :smile:

**Comment by mike-lischke** [comment]
It's not like that in the typings.

**Comment by sharwell** [comment]
I'll look at this and see which way would be cleanest. :smile:

> It's not like that in the typings.

I'm guessing the compiler omits types for private properties.

**Comment by sharwell** [comment]
It looks like this field is unused in the TypeScript target and can simply be removed. :smile:

**Comment by mike-lischke** [comment]
Right, this is nothing for internal use, but rather a nice a debugging help. Removing it wouldn't help with that 😉

**Comment by sharwell** [comment]
If I remove the `const` modifier, you could do this:

```typescript
let s: ATNState = ...;
let kind = ATNStateType[s.stateType];
```

**Comment by mike-lischke** [comment]
And that returns the type as a string? How neat is that? OK, then I'm fine with this.

**Comment by mike-lischke** [comment]
When will you finish that? Not much has happened in the repo since Jan 8 and you are still missing a readme in your published node module.

**Comment by BurtHarris** [comment]
@mike-lischke does PR #291 address your concerns here, or is there more?    I was wondering if the `toString()` method should should use the serializationName, but it's not clear to me if this is exclusively a debugging method .

**Comment by mike-lischke** [comment]
Hmm, I believe the necessary change has already been done there (removal of the const keyword). I tried that locally by changing the code in the node_module folder and it worked. It's just this must be published finally so that users of my node modules don't get a compiler error.

**Comment by BurtHarris** [comment]
OK, I see, thanks.

**Comment by BurtHarris** [comment]
I'm going to make the assumption this has been fixed and close the issue.

**Comment by BurtHarris** [comment]
@mike-lischke I've just got a better fix.   Sam's comment from January 27 about removing the`const` on ATNStateType was right on.   After the following PR, you should be able to use enum `ATNStateType` to lookup the serialization names.
