### ISSUE TITLE
Compile errors using Typescript 2.2.1

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#285]
Installed the latest typescript build (2.2.1) and tried building antlr4ts w/ `npm install`.   During the **tsc** step it generated errors that seem reasonably related to the new features in TypeScript 2.2.    I'll dig into them.

Result:
```
src/Parser.ts(81,59): error TS2344: Type 'string' does not satisfy the constraint 'object'.
src/Parser.ts(810,4): error TS2322: Type 'RuleContext | undefined' is not assignable to type 'RuleContext'.
  Type 'undefined' is not assignable to type 'RuleContext'.
src/dfa/DFAState.ts(173,56): error TS2345: Argument of type 'DFAState | undefined' is not assignable to parameter of type 'DFAState'.
  Type 'undefined' is not assignable to type 'DFAState'.
src/dfa/DFAState.ts(179,53): error TS2345: Argument of type 'DFAState | undefined' is not assignable to parameter of type 'DFAState'.
  Type 'undefined' is not assignable to type 'DFAState'.
```

**Comment by BurtHarris** [comment]
Verified this compiles w/o error under Typescript 2.1.6

**Comment by sharwell** [comment]
> Type 'string' does not satisfy the constraint 'object'.

This should be `Map<string, ATN>` instead of `WeakMap<string, ATN>`.

> Type 'RuleContext | undefined' is not assignable to type 'RuleContext'.

I would hope this is a compiler bug. Fascinating.

**Comment by BurtHarris** [comment]
Thanks Sam, that's good to know.   

The 3rd and 4th errors are something else entirely, it seems that interface **Map**'s `set` method declaration has narrowed the value argument, which used to be marked with a question mark, making undefined an acceptable value.    That question mark got removed in the new version of lib.es2015.collection.d.ts.
