### ISSUE TITLE
tslint: interface name must start with a capitalized I

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#293]
The [default tslint ruleset](https://palantir.github.io/tslint/rules/interface-name/) calls for an "I" prefix on Interface names.  
On the other hand, this [basarat's style guidelines](https://basarat.gitbooks.io/typescript/content/docs/styleguide/styleguide.html#interface) say to avoid the "I" prefix.

Shall we adopt the "I" convention or suppress it?

@sharwell: I can go either way on this, happy to defer a decision to you, I can implement it either way with a rule, see https://palantir.github.io/tslint/rules/interface-name/   

With this issue entered to track it, I'll suppress **interface-name** in **tslint.json** for now.

**Comment by InCodingNowLiu** [comment]
@BurtHarris What the current status of this?
