### ISSUE TITLE
Mac/Linux Continious Integration (Appveyor or Travis CI)

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#302]
We have implemented [Appveyor](https://ci.appveyor.com) for CI on Windows, but it seems like we need something similar for Mac/Linux integration too.   I don't know if Appveyor can do Linux builds too, I know there is also [Travis CI](https://travis-ci.org/).

Bug #283 started out as something else, but current discussion seems to be a Mac/Linux build issue.

**Comment by BurtHarris** [comment]
Attached is a zip archive containing the .travis.yml file I started to work on.   With this, Travis CI seems to repro issue #303 .   
[travis.zip](https://github.com/tunnelvisionlabs/antlr4ts/files/834951/travis.zip)

**Comment by sharwell** [comment]
:memo: For reference, the attached .travis.yml file is as follows:

```yml
language: node_js
before_script:
  - mvn -v
node_js:
  - "6"
```
