### ISSUE TITLE
Add Visitor example

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#305]
The implementation of visitors differs significantly from other ANTLR4 targets and hence needs specific documentation. Especially the fact that the AbstractParseTreeVisitor is not used at all and generated visitors are interfaces, not classes needs some extra considerations. Please add a code example how visitors have to be implemented correctly with the antlr4ts target.

**Comment by sharwell** [comment]
@mike-lischke You should be able to declare a class that extends `AbstractParseTreeVisitor<Result>`. The `defaultResult` method is required, but otherwise it should work like one in Java.

```typescript
class MethodCount extends AbstractParseTreeVisitor<number> implements JavaVisitor<number> {
	protected defaultResult(): number {
		return 0;
	}

	protected aggregateResult(aggregate: number, nextResult: number): number {
		return aggregate + nextResult;
	}

	visitMethodDeclaration(ctx: MethodDeclarationContext): number {
		// One for the current, plus any reported by children
		return 1 + super.visitChildren(ctx);
	}
}
```

**Comment by mike-lischke** [comment]
You missed an important fact: AbstractParseTreeVisitor is not used in generated code! Instead my listener is generated as:

    export interface ANTLRv4ParserVisitor<Result> extends ParseTreeVisitor<Result> {

which has 2 problems: 1) it's an interface, not a class and 2) it doesn't implement the important visit() and visitChildren methods (they are in the AbstractParseTreeVisitor class).

Additionally, the generated visitXXX methods are properties, not methods I can override like in any other target. So I think we have 2 issues here: the generated code is wrong and the use of properties instead of methods, which is why an example would be good to point out the differences to other targets.

**Comment by sharwell** [comment]
@mike-lischke I agree that an example is good, and I don't plan to close this issue until one gets added. I'm just trying to unblock you by providing an initial sample here in the issue. :)

> AbstractParseTreeVisitor is not used in generated code

The use of `AbstractParseTreeVisitor<Result>` is not required. If you want the `visit` method to have default behavior like you see in the Java target, just add `extends AbstractParseTreeVisitor<Result>` to the class which implements the visitor interface. Otherwise, leave it out and you can provide your own implementations of the `ParseTreeVisitor<Result>` interface methods which do whatever you want.

> Additionally, the generated visitXXX methods are properties, not methods I can override

In JavaScript, methods are just properties which have a function type. Special syntax is provided if you want to declare them in a manner which makes them look like methods, but you can also declare them as properties which have a function type. The advantage of the property syntax is it allows you to declare the property as optional. Other target languages don't have this concept.

In my example above, the `visitMethodDeclaration` visitor method defines this visitor method:

```typescript
visitMethodDeclaration?: (ctx: MethodDeclarationContext) => Result;
```

The full advantage of this syntax already comes into play with the listeners. *All* properties of the listener interface are declared optional, including the ones in `ParseTreeListener` itself. This allows the user to avoid creating a new class for each listener.

```typescript
// Example where listener is a class
class MyListener implements JavaListener {
  enterMethodDeclaration(ctx: MethodDeclarationContext): void {
    console.log("Found a method");
  }
}

ParseTreeWalker.DEFAULT.walk(new MyListener(), tree);

// Equivalent example where listener is an anonymous object
let listener = {
  enterMethodDeclaration: function (ctx: MethodDeclarationContext): void {
    console.log("Found a method");
  }
};

ParseTreeWalker.DEFAULT.walk(listener, tree);
```

I'm still trying to figure out if it's possible to use the second syntax with visitors where you want to pull in the default implementation from `AbstractParseTreeVisitor<Result>`.

**Comment by sharwell** [comment]
Apparently you can use class expressions:

```typescript
let visitor = new class extends AbstractParseTreeVisitor<number> implements JavaVisitor<number> {
	protected defaultResult(): number {
		return 0;
	}

	protected aggregateResult(aggregate: number, nextResult: number): number {
		return aggregate + nextResult;
	}

	visitMethodDeclaration(ctx: MethodDeclarationContext): number {
		// One for the current, plus any reported by children
		return 1 + super.visitChildren(ctx);
	}
};
```

**Comment by mike-lischke** [comment]
Somehow I'm still trying to use the TS visitor implementation just like I did with Java and C++, but it escapes me :-)

OK, thanks for the infos. I'll check that out in the next days.

**Comment by mike-lischke** [comment]
Ok, the trick is obviously to extend the abstract visitor and implement the generated visitor, interesting:

```
export class RuleVisitor extends AbstractParseTreeVisitor<string> implements ANTLRv4ParserVisitor<string> {
...
}
```

The class expression approach doesn't seem to work if you want to export a class usable by other modules, but you don't need to use them, so I'm fine with the solution now. Your class must implement the `defaultResult()` as a minimum. What's funny is that you can use both normal function syntax or function properties in your visitor then. Both compile fine. Even a mix does:

```
    visitParserRuleSpec(ctx: ParserRuleSpecContext): string {
        if (!ctx.tryGetRuleContext(0, RuleBlockContext)) {
            return "# Syntax Error #";
        }

        let diagram = "ComplexDiagram(" + this.visitRuleAltList(ctx.ruleBlock().ruleAltList()) + ").addTo()";
        this.scripts.set(ctx.RULE_REF().text, diagram);

        return diagram;
    }

    visitRuleAltList = function(ctx: RuleAltListContext): string {
        let script = "Choice(0";
        let alternatives = ctx.labeledAlt();
        for (let alternative of alternatives) {
            script += ", " + this.visitAlternative(alternative.alternative());
        }

        return script + ")";
    }
```

**Comment by sharwell** [comment]
> Your class must implement the `defaultResult()` as a minimum.

This is a limitation imposed by the type system. We can't relax this restriction without changing the return type of each visitor method to include `| undefined`, which would be more intrusive to developers than just requiring the `defaultResult()` method be defined. In C# we would use `default(T)` here, but there is no equivalent construct in TypeScript.

**Comment by BurtHarris** [comment]
Not sure I understand the whole thread, but isn't `new T()` a reasonable substitute for `default(T)`?

**Comment by mike-lischke** [comment]
@BurtHarris no, it's not that, but how to implement an own visitor. The solution for typescript differs from other target languages (where you just derive your visitor from a generated base visitor). And that should be documented somewhere, which is why I asked for an example. Sam gave me the required hints and I was able to continue.

**Comment by fdeitelhoff** [comment]
Is there somewhere a visitor example? Want to implement my own in TypeScript but I'm stuck. :(

@mike-lischke Maybe you can give me a hint how you implemented it?

**Comment by mike-lischke** [comment]
@fdeitelhoff Sure, look at my `RuleVistor` [implementation](https://github.com/mike-lischke/antlr4-graps/blob/master/src/RuleVisitor.ts).

**Comment by fdeitelhoff** [comment]
@mike-lischke Thanks.

Looking at your example I'm not sure what I'm missing. I have the visitor call:

```
const visitor = new SimplexASTVisitor();
const r = visitor.visit(result);
```

And my own visitor implementation:

```
export class SimplexASTVisitor extends AbstractParseTreeVisitor<string> implements SimplexParserVisitor<string> {

  constructor() {
    super();
  }

  protected defaultResult(): string {
    return 'test from default result';
  }

  public visitExpBoolean (ctx: ExpBooleanContext): string {
    console.log(ctx);

    return 'v';
  }
}
```

But no output is visible. I know that I have to call the visit methods I needed (in contrast to the listener) but what am I missing? Should the visit method not call something?

**Comment by BurtHarris** [comment]
> ... but that's how Sam and Burt want antlr4ts to be implemented

Not necessarily how I want it implemented, I'm convinced the "tryGet" stuff is bogus.   Sam and I just haven't finished working it out yet.   Please be patient.

**Comment by mike-lischke** [comment]
@BurtHarris ah, didn't know you're still thinking about it. In my editor extension invalid syntax is the normal case and I must be able to get as many symbols as I can, so I have to be prepared to handle any missing parse context.

@fdeitelhoff Hm, difficult to say without full code. These functions are now implemented as (optional) properties, I'm not sure if you can just override them like normal functions. Try to assign functions as I did in my visitor. Also make sure you use input that actually creates a parse tree which contains parse contexts for which you have visitor functions. If all fails step through the antlr4ts code to see what happens.

**Comment by BurtHarris** [comment]
@mike-lischke, @fdeitelhoff  see issue **#196 Doing away with BaseListener classes** for background on those optional methods.   (The idea got extended to Visitors as well.)

We are still open to feedback on this, the idea seems good but there may be some adjustments needed to refine it.   

Due to JavaScript's lack of synchronous I/O operations, how to adjust the style of ANTLR parsers to support async operation has been a bit of a nagging concern for me.   In the current version we've sort of punted it by only supporting a synchronous parse model, requiring all parse input at once.

**Comment by yifanwu** [comment]
Hi, this might be a silly question but when I was extending the visitor I had to add the following (`visit`, `visitChildren` etc) for Typescript not to complain...

I saw the code @mike-lischke linked [here](https://github.com/mike-lischke/antlr4-graps/blob/master/src/RuleVisitor.ts) but wasn't sure if `extends AbstractParseTreeVisitor<string>` applies to normal uses of antlr --- it seems like the project is a tool for antlr (or maybe I'm just confused!).

```export default class SimpleVisitor implements visitor.VQLVisitor<ExpressionValue> {

  visit = (ctx: any): any => {
    return ctx.accept(this);
  }

  // HACKs
  visitTerminal = (ctx: any): any => {
  }

  visitErrorNode = (ctx: any): any => {
  }

  visitChildren = (ctx: any): any => {
  }

  // below are my actual application logic for visiting different parts of the tree

```

Thanks for the help!

I am currently working on a project with antlr4ts and happy to write up an example PR if I debug through my code.

**Comment by sharwell** [comment]
So I think I finally figured out what the expected behavior here should be. From what I can tell, whenever input is successfully parsed there is no problem with the way the tree nodes are implemented.

In addition, there never appeared to be any disagreement that the current definition of the tree nodes was inaccurate. The only problem was a question of usability in the case of processing inputs with syntax errors. This leads me to believe that the source of the problems is not in the tree nodes, but in the error recovery mechanism. During error recovery, the tree nodes should be updated to contain zero-length tokens/nodes for the shortest path to the end of the rule, ensuring that even when processing trees with errors the properties of tree nodes behave as expected.

**Comment by BurtHarris** [comment]
@yifanwu, thanks for speaking up.   As I understand it, using `extends AbstractParseTreeVisitor<Result> on your visitor class` *conceptually* is optional, but you will probably want to do it no matter what grammar you are supporting.   If you don't extend from `AbstractParseTreeVisitor<Result>` you would need to provide your own implementations of `visit`, `visitChildren`, `visitTerminal`, and `visitChildren`.  that return the proper type (e.g. `string` in Mike's example.)  

The idea we were going for in pull request #200 was that application-specific visitors might not require a class at all, and could potentially be implemented as an object literal, but creating a Visitor class will continue to be a support option.   The object-literal idea hasn't been fully fleshed out yet, but if your sample is simple perhaps we can do so together.     If you are willing, please share a link to your full project when so we can take a look.

@sharwell, that sounds like a promising insight.

**Comment by yifanwu** [comment]
Hey @BurtHarris thanks for explaining --- I added the `extends` and also the `defaultResult` and it appears to be working.

Wrt the object literal implementation --- I don't think I'm familiar enough to chive in there --- I was more thinking of helping create a calculator example with the visitor pattern for documentation.  Let me know if that'd be useful.  It does seem a bit different from the c# usages (which I started with), esp with the object literal implementation.

**Comment by fdeitelhoff** [comment]
@yifanwu A more or less complete visitor example would be very useful. I'm still stuck while implementing it.

Maybe you an send it via a Gist so we can discuss it? Hopefully there will be a complete example at the end of our discussion so we can send a PR.

Thanks!

**Comment by adityapurwa** [comment]
There is no `AbstractTreeVisitor` inside antlr4ts, am I missing anything?

**Comment by mike-lischke** [comment]
The class is `AbstractParseTreeVisitor`.  See Sam's answer to my initial question.

**Comment by amilner42** [comment]
I'm struggling myself, I could use a hand if someone know's what's wrong with this, it doesn't seem to be calling my visitor methods:

```javascript
// < imports >
class ExtractCommentsAndFunctionsVisitor extends AbstractParseTreeVisitor<any> implements JavascriptParserVisitor<any> {

    constructor() {
        super()
    }

    defaultResult(): number {
        return 0;
    }

    visitTerminal(node: any) {
        console.log("Prints")
    }

    visit(parseTree: any) {
        // Nothing prints
        console.log("VISIT")
    }

    visitProgram(node: any) {
        // Nothing prints
        console.log("HERE")
    }
}

// TODO
// Create lexer and parser
let inputStream = new ANTLRInputStream("// comment; \n () => { }");
let lexer = new JavascriptLexer(inputStream);
let tokenStream = new CommonTokenStream(lexer);
let parser = new JavascriptParser(tokenStream);
let result = parser.program(); // Parse our program
const visitor = new ExtractCommentsAndFunctionsVisitor();

ParseTreeWalker.DEFAULT.walk(visitor, result)
```

I don't understand why it's not printing anything in `visitProgram`, am I  missing something?

Thanks!

**Comment by amilner42** [comment]
@sharwell 

If you happen to see something obviously wrong with what I'm doing, I'd appreciate knowing, but no problem at all if you're busy, Ill figure it out, thanks!

**Comment by sharwell** [comment]
> `ParseTreeWalker.DEFAULT.walk`

This is the entry point for listeners.

For visitors, just call `visitor.visit(result)`.

**Comment by amilner42** [comment]
Makes sense, thanks, would you like me to add a few lines to the README (at the bottom) and submit a PR so that it's more clear to future people how to proceed after:

```
// Parse the input, where `compilationUnit` is whatever entry point you defined
let result = parser.compilationUnit();
```

Let me know @sharwell

**Comment by sharwell** [comment]
@amilner42 Sure

**Comment by amilner42** [comment]
Created a [pull request](https://github.com/tunnelvisionlabs/antlr4ts/pull/404) with strictly doc changes.

Sorry for the delay, had to finish some code, cheers @sharwell
