### ISSUE TITLE
Implement ANTLRFileStream

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#320]
I've figured out we *can* implement an `ANTLRFileStream` class for Node.js.

Previously I didn't think this was possible because the [`stream`](https://nodejs.org/dist/latest-v6.x/docs/api/stream.html) API are all async with a callback style interface.   However, there are synchronous read (and write) interfaces in the [`fs`](https://nodejs.org/dist/latest-v6.x/docs/api/fs.html) module, they just don't implement the `stream` semantics.   

We should however mention in the docs that this class is strictly for use in command-line applications (and the like) and not for server or UI application where a responsive event loop is desired.

@sharwell I've launched into this several times now trying to update `ANTLRInputStream` to be based on [`Buffer`s](https://nodejs.org/dist/latest-v6.x/docs/api/buffer.html) rather than `string`s.   That seems like a simple matter, but I keep breaking the unit tests.   It seems to me like I must be getting `getText()` wrong, the rest of it just doesn't seem hard enough to screw up.   Is there anything special I should know?

**Comment by BurtHarris** [comment]
Maybe I should be looking at the UnbufferedCharStream to base this on.   The "default" for on Node.js is utf-8.   My previous attempts have been to map this to 'utf-16le', but if the logic for decoding the utf-8 on the fly is built into the input stream..., utf-8 might have better performance for the typical case.   

The `Unbuffered` in that classes name has previously put me off, but now that I read the docs on it, it seems like a better design than ANTLRInputStream.

**Comment by BurtHarris** [comment]
@sharwell It looks to me like we could gain a significant performance advantage by redefining `interface CharStream` slightly.   We could get rid of `LA(i: number): number`, and replace it by a `readonly cp: number`.   

1,214 occurrences of `.LA(` in source files, including both `.ts` and `.tssoon` files, 
1,181 of those are `.LA(1)`
33 remaining (non-`.LA(1)`) references, 
    - 10 of them in `benchmark\JavaUnicodeInputStream.ts`
    - 21 in `test\` directories, mostly in `test\tool\TestUnbufferedCharStream.tssoon`
    - 2 remain in `src`:

```typescript
src\ANTLRInputStream.ts:87:       return this.LA(i);
src\DefaultErrorStrategy.ts:531:   let nextTokenType: number = recognizer.inputStream.LA(2);
```
So, it seems, the only one interesting place where `.LA()` is called looking for any real look ahead is in `DefaultErrorStrategy`, and there it's only looking for 1 unit of lookahead (and I note that is dealing with TokenStream rather than CharStream!).

**Comment by sharwell** [comment]
The real problem isn't the stream implementation, but the fact that the lookahead implementation requires the stream be synchronous.

**Comment by BurtHarris** [comment]
I think there are three broad use-cases we need to consider, with a fourth possible in some future

1.  Simple Node.js command line applications.   This is the market for ANTLRFileStream.  In these applications a responsive event loop is unimportant, but handling potentially large files is.   

2.  Scalable Node.js server applications.

3.  Browser-based applications.

4.  Some streaming `async` parsing model (maybe, someday)

**Comment by BurtHarris** [comment]
Will track in the future under asynch
