### ISSUE TITLE
TS 2.6 `strictFunctionTypes` causes compilation error with `RuleVersion` decorator

### ISSUE THREAD

**Issue by jessezhang91** [tunnelvisionlabs/antlr4ts#345]
TypeScript 2.6 introduced the compiler option `strictFunctionTypes`. The generated ANTLR4 TypeScript code has a compilation error with the `RuleVersion` decorator due to the `ParserRuleContext` in the `TypedPropertyDescriptor` in its declaration.

I think the way to fix it is:

In: https://github.com/tunnelvisionlabs/antlr4ts/blob/5bdb06c3fa458fd07f0fad67b33903b85b41e9bc/src/RuleVersion.ts#L15-L20

Add a type parameter to `RuleVersion<F extends ParserRuleContext>` and change the `ParserRuleContext` in the function to be `F`:
```typescript
export function RuleVersion<F extends ParserRuleContext>(version: number) {
	return function(target: Parser, propertyKey: PropertyKey, propertyDescriptor: TypedPropertyDescriptor<(...args: any[]) => F>) {
	};
}
```

Then in:
https://github.com/tunnelvisionlabs/antlr4ts/blob/f49ceb30f273542da3978e97c7298b1c9fe7ba1c/tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg#L275

Add the type parameter of the corresponding rule context:
```
@RuleVersion\<<currentRule.ctxType>\>(<namedActions.version; null="0">)
```

Thanks!

P.S. From my single project, this was the only thing breaking when I use the `strictFunctionTypes` compiler option. There may be other issues that need to be fixed.

**Comment by BurtHarris** [comment]
Thanks for reporting this @jessezhang91.   I'm looking at another typescript 2.6 issue when building the package right now, so I'll try to tackle them both.

By the way, typescript errors are non-fatal (perhaps they should be considered warnings.)

**Comment by BurtHarris** [comment]
Thanks for the fix, @jessezhang91, it looks good to me.    Impressive work.

**Comment by jessezhang91** [comment]
Thank you for looking into it and supporting this library!
