### ISSUE TITLE
message TS4090: Conflicting definitions for 'node' found ...

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#348]
Build of tsc 2.6 branch generates the following error:

message TS4090: Conflicting definitions for 'node' found at 'C:/code/antlr4ts/node_modules/@types/node/index.d.ts' and 'C:/code/antlr4ts/node_modules/@types/mocha/node_modules/@types/node/index.d.ts'.  Consider installing a specific version of this library to resolve the conflict.

**Comment by zhangchri** [comment]
delete other reference module, update package-lock.json config file

**Comment by sharwell** [comment]
This was not reproducible for me on a clean clone and build this weekend.
