### ISSUE TITLE
Parent conflict between `RuleContext` and `ParseTree`

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#355]
The class `RuleContext` introduces a specialized parent member, which is not compatible with the parent member used in `ParseTree`. This make it impossible to use a common `ParseTree` member variable, e.g. in a symbol table, for both rule contexts and terminal nodes. In Java und C++ this is possible without problems.

**Comment by sharwell** [comment]
💭 The intent was this member would be usable in the manner it seems you are describing.

Can you put together a small sample showing the incompatibility? I'd like to add it as a test so we can validate a fix and prevent regressions.

**Comment by mike-lischke** [comment]
The easiest is probably to check out the debugger branch from [antlr4-graps](https://github.com/mike-lischke/antlr4-graps/). This is what I get in vscode:

![vscode-errors](https://user-images.githubusercontent.com/2398704/35815284-6846c798-0a98-11e8-9e07-66d47f5bae62.png)

**Comment by mike-lischke** [comment]
Hmm, weird. While trying to put together another example I cannot reproduce the problem:

    it.only("Parse Tree Parent Test", function () {
        let symbolTable = new c3.SymbolTable("Temp", { allowDuplicateSymbols: false });
        let classSymbol = symbolTable.addNewSymbolOfType(c3.ClassSymbol, undefined, "classX");
        let context: ParserRuleContext | undefined;
        classSymbol.context = context;
        let token: TerminalNode | undefined;
        classSymbol.context = token;
    });

compiles and executes just fine. So it must be something in my graps code.

Btw, in order to reproduce with the graps code you need to change the `antlr4-c3.Symbol.context` member from `ParserRuleContext` to `ParseTree`. I haven't yet published this change.

**Comment by mike-lischke** [comment]
Meanwhile I believe it's a Typescript problem. The code runs fine without any problem.

**Comment by mike-lischke** [comment]
I tried to cast the context to a `ParseTree`, only to get this error:

> file: 'file:///Volumes/Extern/Work/projects/antlr4-graps/src/DetailsListener.ts'
severity: 'Error'
message: 'Type 'ParseTree' is not assignable to type 'ParseTree | undefined'.
  Type 'ParseTree' is not assignable to type 'ParseTree'. Two different types with this name exist, but they are unrelated.
    Types of property 'parent' are incompatible.
      Type 'ParseTree | undefined' is not assignable to type 'ParseTree | undefined'. Two different types with this name exist, but they are unrelated.
        Type 'ParseTree' is not assignable to type 'ParseTree | undefined'.
          Type 'ParseTree' is not assignable to type 'ParseTree'. Two different types with this name exist, but they are unrelated.'

However, I triple checked, there are no 2 different `ParseTree` classes. But I have antlr4ts in both projects (antlr4-c3 and antlr4-graps). So far this did not produce any problem. I'd much appreciate any idea what could be done to solve this.

**Comment by mike-lischke** [comment]
It's a Typescript problem caused by a linked node module.

**Comment by sharwell** [comment]
That has been a frustratingly common statement at the end of too many things I've tried.

**Comment by BurtHarris** [comment]
@mike-lischke are you saying it is due to use of the npm link feature?

**Comment by mike-lischke** [comment]
@BurtHarris Yes, that's the reason. I frequently use that to link my node/vscode projects together. However, both antlr4-graps as well as antlr4-c3 have a dependency to antlr4ts and with npm links the TS transpiler not only sees JS files, but all the TS sources as well. Hence the trouble.

**Comment by BurtHarris** [comment]
@mike-lischke  thanks, I think I understand, where both the original .ts and .d.ts files become visible.   

I've worked on a couple of solutions for that but got a bit frustrated with the complexity.   I'll try to resurrect and review the branches where I addressed this, and see if I can isolate just the changes needed to avoid the problem.

**Comment by mike-lischke** [comment]
It's not the original antlr4ts source. In both cases we only have the type definitions (each one included by a node module I wrote).

However, it's not a big deal. Not ideal, but I can copy the JS/TS files manually if needed. It's only extra work for changes I haven't published yet. Much more important would be to get an antlr4ts 1.0 ;-)
