### ISSUE TITLE
Profiling unsupported

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#356]
Now that I have my vscode debugger almost ready I wanted to add profiling support for grammars, only to get an exception that this is not supported. What are your plans wrt to this? What's missing for profiling a grammar?

**Comment by sharwell** [comment]
> only to get an exception that this is not supported

What exception did you get? I would need to look back at the way profiling is implemented for other targets to see what's needed here.

**Comment by mike-lischke** [comment]
The code is here: https://github.com/tunnelvisionlabs/antlr4ts/blob/master/src/Parser.ts#L860. Looking at the [ProfilingATNSimulator](https://github.com/tunnelvisionlabs/antlr4ts/blob/master/src/atn/ProfilingATNSimulator.ts) gives the impression that it would be ready to use. Only the parser needs to be enabled for that.

**Comment by mike-lischke** [comment]
I enabled profiling locally and it looks pretty good:

![antlr4-profile](https://user-images.githubusercontent.com/2398704/36851568-c8ae75e8-1d69-11e8-84a7-d83f78c1d790.png)

Only a few things are missing (input and DFA for example).

**Comment by sharwell** [comment]
> In fact the TS profiler has more content than other runtimes (e.g. SimulatorState, which doesn't exist in C++ and Java).

This target is based on my optimized fork, similar to tunnelvisionlabs/antlr4 and tunnelvisionlabs/antlr4cs. Most of the changes are documented here:
https://github.com/tunnelvisionlabs/antlr4/blob/master/doc/optimized-fork.md

**Comment by sharwell** [comment]
> I enabled profiling locally and it looks pretty good:

Awesome. I totally forgot we integrated this into the runtime. I believe it's derived from work originally done for ANTLRWorks 2 in the early days of ANTLR 4.

**Comment by mike-lischke** [comment]
When can we get the fix, read: when will be the next official release?
