### ISSUE TITLE
ERROR TypeError: Class constructor Lexer cannot be invoked without 'new'

### ISSUE THREAD

**Issue by tawalters61** [tunnelvisionlabs/antlr4ts#394]
I just tried using antlr4ts for the first time... and got the following error:

ERROR TypeError: Class constructor Lexer cannot be invoked without 'new'

This occurs at the time I attempt to create the Lexer for my DSL.

Any ideas?

Thanks.

**Comment by lujun2** [comment]
It may related to your `tsconfig.json`, try use `es6` as your compile target

```json
{
  "compilerOptions": {
     "target": "es6",
  }
}
```

**Comment by tawalters61** [comment]
Thanks. This worked.

**Comment by sharwell** [comment]
@lujun2 This project uses `es2015` as the target. Do you know which targets I should expect to work and which ones not?

**Comment by piotrl** [comment]
It seem it does not work with `es5` target (sadly, as it's still default target for many projects)
