### ISSUE TITLE
Visitors not working; XVisitor does not exist.

### ISSUE THREAD

**Issue by iiian** [tunnelvisionlabs/antlr4ts#398]
Visitor implementers asking me to implement methods like `visit(tree: ParseTree): Result;`
Header of ParseTreeVisitor.d.ts says:
```
 * This interface defines the basic notion of a parse tree visitor. Generated
 * visitors implement this interface and the {@code XVisitor} interface for
 * grammar {@code X}.
```

Tried a few versions, none seem stable with Visitor. Just wondering, is this supported yet?

**Comment by sharwell** [comment]
Yes, this feature should be supported in the current release. 😄

**Comment by iiian** [comment]
Oooooh... yeah, I was passing the visitor argument. I ended up implementing my small grammar with the javascript antlr4 target because I couldn't figure out how to get/find XVisitor in my project. Is that because XVisitor gets generated by the code generator?

**Comment by iiian** [comment]
Thanks for responding, Sam, I'm sorry I didn't see this sooner.

**Comment by sharwell** [comment]
> Is that because XVisitor gets generated by the code generator?

Yes, it is generated by the code generator.
