### ISSUE TITLE
Lexer fails to lex valid input

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#406]
antlr4ts still doesn't support Unicode fully like ANTLR4 does, however it should at least fully handle the Unicode BMP. I'm writing a sentence generator which created this valid cyrillic string: `"ҔҳѪⷲԭԧѯѻӇꙅꙒӜһԤѾꙦ"` (the JS code for that is: "\u{A671}\u{494}\u{4B3}\u{46A}\u{2DF2}\u{52D}\u{527}\u{46F}\u{47B}\u{4C7}\u{A645}\u{A652}\u{4DC}\u{4BB}\u{524}\u{47E}\u{A666}"). You can check in the Unicode Database that all these characters are valid cyrillic code points. Yet when I lex this string I get errors:

```
AssertionError: Generated input "꙱ҔҳѪⷲԭԧѯѻӇꙅꙒӜһԤѾꙦ" for rule "cyrillicIdentifier" generated error:
Lexer error (1, 1): token recognition error at: '꙱'
Lexer error (1, 2): token recognition error at: 'Ҕ'
Lexer error (1, 3): token recognition error at: 'ҳ'
Lexer error (1, 4): token recognition error at: 'Ѫ'
Lexer error (1, 5): token recognition error at: 'ⷲ'
Lexer error (1, 6): token recognition error at: 'ԭ'
Lexer error (1, 7): token recognition error at: 'ԧ'
Lexer error (1, 8): token recognition error at: 'ѯ'
Lexer error (1, 9): token recognition error at: 'ѻ'
Lexer error (1, 10): token recognition error at: 'Ӈ'
Lexer error (1, 11): token recognition error at: 'ꙅ'
Lexer error (1, 12): token recognition error at: 'Ꙓ'
Lexer error (1, 13): token recognition error at: 'Ӝ'
Lexer error (1, 14): token recognition error at: 'һ'
Lexer error (1, 15): token recognition error at: 'Ԥ'
Lexer error (1, 16): token recognition error at: 'Ѿ'
Lexer error (1, 17): token recognition error at: 'Ꙧ'
```

The used rules are:

```
cyrillicIdentifier: CyrillicIdentifier;
CyrillicIdentifier: CyrillicChar+;
CyrillicChar: [\p{Script=Cyrillic}];
```

Other generated content with ANSI input (e.g. keywords, simple strings from the Latin range, numbers etc.) all parse fine. However, the used setup for this generator is a bit special, which might play a role here: the lexer ATN was created with ANTLR4 (exported as interpreter data), not antlr4ts and then loaded with a special version of the antlr4ts ATN deserializer class. This class does not expect the extensions from antlr4ts (which prevents loading interpreter data generated with the official ANTLR4 tool). The code for this custom class [can be found on Github](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/backend/CompatibleATNDeserializer.ts) as well.

Though, I don't think the setup is the culprit. The ATN for the relevant rule is correct, so it should parse correctly:

<img width="727" alt="screenshot" src="https://user-images.githubusercontent.com/2398704/53298731-48a7fd80-3832-11e9-92fb-2ae7d7b26ead.png">

I rather believe something in the input stream handling is not correct.

**Comment by mike-lischke** [comment]
I just realized, I made a mistake and mixed lexer and parser tests wrongly.

**Comment by sharwell** [comment]
@mike-lischke I sent a pull request last week to antlr4ts that adds the rest of the Unicode features.
