### ISSUE TITLE
[FR] Make ATNDeserializer compatible with ATN data from standard ANTLR4

### ISSUE THREAD

**Issue by mike-lischke** [tunnelvisionlabs/antlr4ts#407]
The antlr4ts tool uses a number of optimizations, which also leave some traces in the serialized ATN, which in turn makes that incompatible to the standard ATN stream from ANTLR4. Now, with the possibility to use exported interpreter data (*.interp files), it would be very helpful to be able to load both, the standard format and the extended format with the same deserializer. Currently I have to use [a copy of the antlr4ts ATNDeserializer class](https://github.com/mike-lischke/vscode-antlr4/blob/master/src/backend/CompatibleATNDeserializer.ts), in order to be able to load standard ATN data from such files.

**Comment by sharwell** [comment]
> Currently I have to use a copy of the antlr4ts ATNDeserializer class, in order to be able to load standard ATN data from such files.

I believe this is the expected approach, since the ATN from the reference release is otherwise not usable by this runtime.

**Comment by mike-lischke** [comment]
It wasn't very difficult to make it compatible (even though I don't oversee all the implications caused by my own class, since I simply ignore the additional stuff added by antlr4ts). So it looks as if it is pretty simply to make the antlr4ts ATN deserializer compatible with both ATN variants.

**Comment by mike-lischke** [comment]
And yet another change appeared in the latest antlr4ts release (0.5.0-alpha.3): the UUID for ADDED_UNICODE_SMP changed from "59627784-3BE5-417A-B9EB-8131A7286089" to "C23FEA89-0605-4f51-AFB8-058BCAB8C91B". Another stumbling stone to use reference ANTLR4 generated ATNs with antlr4ts - pretty annoying.

Again, please consider making antlr4ts compatibile with the reference release. Stuff added by antlr4ts can be made optional and would allow to load ATNs for all supported platforms using antlr4ts. Thanks.

**Comment by sharwell** [comment]
> And yet another change appeared in the latest antlr4ts release (0.5.0-alpha.3): the UUID for ADDED_UNICODE_SMP changed from "59627784-3BE5-417A-B9EB-8131A7286089" to "C23FEA89-0605-4f51-AFB8-058BCAB8C91B"

This change was made in d6d151bb70d6081c94545bd8c999e89b3d2e4c0f, correcting a mistake made in 51f40aba693793b0ce99c3a19a5c82f13cb7fac0. antlr4ts does not support the ATN format with GUID 59627784-3BE5-417A-B9EB-8131A7286089, which is a format produced by the reference Java version of the tool.

A few years ago, the maintainers of the reference version turned down a proposal to maintain compatibility across the forks. I recommend treating the ATNs from the reference release as an independent data format, where the deserializer for this format is maintained as part of the application code that needs to use it. antlr4ts has no need to produce or use this data, and no plans to natively support it.

**Comment by mike-lischke** [comment]
OK, but I guess antlr4ts will never support other targets than Typescript, which means it is impossible to write tools that support (generation and debugging of) all normally supported targets. A severe limitation actually, from a tool writer's perspective.

**Comment by sharwell** [comment]
The project licensing should allow tools to include a modified copy of ATNDeserializer which supports other input formats.
