### ISSUE TITLE
Dev setup: JDK and Maven versions?

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#418]
I flattened my dev box a while back, and wanted to catch up with antlr4ts.   Walking through the instructions in CONTRIBUTING.md, it talks about installing JDK and MAVEN, and gives minimum versions.   After reading issue #374, I'm confused what versions to install.  

A nice-to-have would be hyperlinks to the recommended install web-pages.

**Comment by sharwell** [comment]
Historically I used JDK 8 with Maven 3.x. On this machine I see JDK 8, 10, and 11 with Maven 3.6.0.
