### ISSUE TITLE
Cannot find name 'getCharPositionInLine' in generated Lexer

### ISSUE THREAD

**Issue by gsongsong** [tunnelvisionlabs/antlr4ts#424]
For example, with a grammar like below, generated Java lexer supports `getCharPositionInLine()`. However, TS lexer generated with antlr4ts seems not support `getCharPositionInLine()`. Or did I miss something?

```
LINE_COMMENT
    : {getCharPositionInLine() == 0}? (' ' | '\t')*? '--' ~('\n'|'\r')* '\r'? '\n' ->skip
    ;
```

**Comment by gsongsong** [comment]
I suspect replacing it to `this.charPositionInLine` might solve the problem.

**Comment by sharwell** [comment]
Code inside grammar predicates is language-specific. JavaScript requires instance members be qualified with `this.`, where other languages do not.

**Comment by gsongsong** [comment]
@sharwell Thanks for comment. But as mentioned above seems `this.charPositionInLine` is the one. (not function but property)
