### ISSUE TITLE
TerminalNodeImpl missing in antlr4ts

### ISSUE THREAD

**Issue by caroe233** [tunnelvisionlabs/antlr4ts#425]
Hi Guys,

It might be me being stupid but can someone explain to me what it is about TerminalNode vs TerminalNodeImpl? It seems that antlr4 typically uses TerminalNodeImpl which extends TerminalNode. In antlr4ts most of the code assumes there only is TerminalNode. However, when I start debugging I do actually have an instance of TerminalNodeImpl which then doesn't match the code. See one example here:

![image](https://user-images.githubusercontent.com/38064741/64121750-068ee400-cda0-11e9-978c-5d183d49168d.png)

This is within the ParseTreeWalker. It checks on "instanceof TerminalNode" but what I really get is a TerminalNodeImpl which also has different properties than TerminalNode (parentCtx instead of parent and symbol instead of _symbol). So the walker doesn't ever realize it reached a terminal node because the instance of check doesn't match.

Also, when writing my own code. I am trying to access parentCtx of my TerminalNode and I can't because of the mismatch in typings.

Is there help files about this that I oversaw? Can anyone explain to me how to handle this please?

**Comment by sharwell** [comment]
antlr4ts dropped the `TerminalNode` interface, and renamed `TerminalNodeImpl` to `TerminalNode`. There is no `TerminalNodeImpl` type in this project, so I'm not sure where that's coming from. 😕

**Comment by caroe233** [comment]
Hi,
I got it working. I think my problem was that I had antlr 4 and antlr4ts mixed. It's looking very good now :)
