### ISSUE TITLE
Ship `.ts` sources or turn on `--inlineSources`

### ISSUE THREAD

**Issue by DanielRosenwasser** [tunnelvisionlabs/antlr4ts#432]
Hi there!

Today your package ships with `.js.map` files which redirect to `.ts` files that aren't included in the package. This ends up causing build tools (like Parcel) to spill out a ton of warnings.

```
‼  Could not load source file "../../../src/atn/BasicState.ts" in source map of "../node_modules/antlr4ts/atn/BasicState.js".
```

![image](https://user-images.githubusercontent.com/972891/71528541-26896c80-2895-11ea-9c63-86dc36a0ec50.png)

I would suggest either removing the sourcemaps entirely, or shipping the `src` directory as well.

**Comment by sharwell** [comment]
Is there something like SourceLink for TypeScript (metadata points to a specific commit on GitHub where the sources can be obtained)?

**Comment by DanielRosenwasser** [comment]
Unfortunately not that I know of - although, as I realized that instead of shipping `.ts` files, you can turn on `inlineSources` to emit the `.ts` contents within the `.js.map` files. Ultimately it's up to you.

**Comment by BurtHarris** [comment]
I think the .ts files should be included in the NPM package too.
