### ISSUE TITLE
Can't find BaseErrorListener

### ISSUE THREAD

**Issue by NikiforovAll** [tunnelvisionlabs/antlr4ts#436]
I can't find `BaseErrorListener` so it could be inherited and used for a custom implementation.

Motivation: I would like to have my own implementation of the listener to facilitate testing. What is the correct way to accomplish this? Should I extend `DiagnosticErrorListener`?

**Comment by fabiannagel** [comment]
It currently seems broken to me: #430

**Comment by BurtHarris** [comment]
The way listeners in general work in the TypeScript port, then need for **Base*Listener** (like `BaseErrorListener`)  classes is eliminated.   In the Java target, these **Base*Listener** carry along empty implementations of all the methods required by the interface definition (e.g. `ErrorListener)`.

In the TypeScript target, we have made **all** the methods optional in the interface definition.   For example, we define:
```ts
interface ParserErrorListener extends ANTLRErrorListener<Token> {
   ...
	reportAmbiguity?: (	
		recognizer: Parser, 
		dfa: DFA, 
		startIndex: number, 
		stopIndex: number, 
		exact: boolean,
		ambigAlts: BitSet | undefined,
		configs: ATNConfigSet) => void;
    ...|
```
Note the question mark in `reportAmbiguity?`, that means you don't _need_ to define `reportAmbiguity` to create a valid `ParserErrorListener`, you can just leave it out.   This allows a very compact notation combining object literals with lambdas:

```
const parser = new ExperParser( tokens );
parser.AddErrorListener( {
    reportAmbiguity: (parser, dfa, startIndex, stopIndex, exact, ambigAlts, configs) => {
         ... report ambiguity as you like. ..
   },
});
const tree = parser.prog();

**Comment by BurtHarris** [comment]
Please reopen this if it's not clear
