### ISSUE TITLE
TS2339: Property 'compilationUnit' does not exist on type 'TagQueryParser'.

### ISSUE THREAD

**Issue by josejulio** [tunnelvisionlabs/antlr4ts#443]
When trying the following code:

```ts
const inputStream = new ANTLRInputStream(localSelection);
const lexer = new TagQueryLexer(inputStream);
const tokenStream = new CommonTokenStream(lexer);
const parser = new TagQueryParser(tokenStream);
const tree = parser.compilationUnit();
                   ^
//        Does not compile
```
Generated with: 
```antlr4ts -visitor `pwd`/TagQuery.g4```

**Comment by josejulio** [comment]
Well, duh!
It should be `tagquery` function as is my entry function, sorry for the spam.

**Comment by sharwell** [comment]
No problem, glad you figured it out!

**Comment by taven-liu** [comment]
Same problem

**Comment by AnimeAllstar** [comment]
@josejulio Hey, I'm new to ANTLR and got the same issue, what'd you change to make it work? Thanks.

**Comment by josejulio** [comment]
`compilationUnit` is the name of your parser entry point. In my case it was something else.
i.e. in [this](https://github.com/RedHatInsights/policies-engine/blob/master/src/main/antlr4/com/redhat/cloud/policies/engine/condition/Expression.g4#L4) instead of `compilationUnit` you might use `expression` - the function varies depending your ANTLR file
