### ISSUE TITLE
TypeScript version upgrade blocked

### ISSUE THREAD

**Issue by BurtHarris** [tunnelvisionlabs/antlr4ts#460]
Strange error behavior if we upgrade to TypeScript version 3.  The tsc command seems to hang or become very slow.

This is related to `import` statements, located outside the runtime's src directory, which use paths including `from "antlr4ts/src/"'...  This causes some sort of recursive compilation behavior.

**Comment by viceice** [comment]
duplicate of #459

**Comment by BurtHarris** [comment]
closing duplicate
