### ISSUE TITLE
Consider using non-null arguments for VocabularyImpl constructor

### ISSUE THREAD

**Issue by sharwell** [tunnelvisionlabs/antlr4ts#50]
The `VocabularyImpl` constructor in #34 was ported rather literally from the original Java code. Since we don't have to worry about legacy generated code in TypeScript (prior to the time when `Vocabulary` was introduced), it might not be necessary to support null values for these constructor arguments. After we have completed more of the port, we can examine all uses of `VocabularyImpl` in generated code and the runtime library to determine if one of the following approaches would be better.
1. Using non-null arguments, and require all values be passed by the caller to the constructor
2. Allowing one or more arguments to be omitted, but providing default values for the parameters so the resulting call is made with non-null arguments

:memo: First mentioned by @BurtHarris in a comment in #34.

**Comment by BurtHarris** [comment]
@sharwell: Reviewing status on this issue.   It seems relatively minor at this point, but all generated invocations of the `new VocabularyImpl` currently come from same the [template](https://github.com/tunnelvisionlabs/antlr4ts/blob/master/tool/resources/org/antlr/v4/tool/templates/codegen/TypeScript/TypeScript.stg#L203) line, using only 2 out of 3 arguments meaningfully.

Reviewing the existing code invoking this, it's not even clear what the use case for the `displayNames` argument is, though I gather it's mainly about debug output, and perhaps even only for cases where a hand-written tokenizer has been written.   We've clearly got no tests which depend on this.

In terms of **ts-flavor**, I think there' slots that *could* be done to tighten up Vocabulary & VocabularyImpl, but not sure it's a good use of time at this point.   We probably ought to discuss at a higher level where to direct energy next...

**Comment by sharwell** [comment]
Fixed by #78
