### ISSUE TITLE
Can't run on an Angular project?

### ISSUE THREAD

**Issue by billbarni** [tunnelvisionlabs/antlr4ts#520]
I am having tons of issues running the examples in simple Angular project.

Do I need different tools? Is there any possibility of building an example project?

I get dependency errors asking for "assert" and "util", after force-installing those I get error and can't start my web app.

util.js:109 Uncaught ReferenceError: process is not defined
    at Object.1305 (util.js:109)
    at __webpack_require__ (bootstrap:19)
    at Object.4715 (assertion_error.js:35)
    at __webpack_require__ (bootstrap:19)
    at Object.1478 (assert.js:36)
    at __webpack_require__ (bootstrap:19)
    at Object.456 (ANTLRInputStream.js:15)
    at __webpack_require__ (bootstrap:19)
    at Object.2580 (index.js:20)
    at __webpack_require__ (bootstrap:19)

What am I doing wrong?

Simple code that I am using:

```
import { Component } from '@angular/core';

import { CharStreams, CommonTokenStream } from 'antlr4ts';
import { JavaLexer } from './java-parser/JavaLexer';
import { JavaParser } from './java-parser/JavaParser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'angular-modeler';

  constructor() {
    console.log(1);
    // Create the lexer and parser
    let inputStream = CharStreams.fromString("text");
    let lexer = new JavaLexer(inputStream);
    let tokenStream = new CommonTokenStream(lexer);
    let parser = new JavaParser(tokenStream);

    // Parse the input, where `compilationUnit` is whatever entry point you defined
    let tree = parser.compilationUnit();

    console.log(tree);
  }

}
```

**Comment by alessiostalla** [comment]
I'm using antlr4ts in an Angular 13 project. It works but Angular complains that it's not an ES module.
_However_ I had to add the following:
```
  "browser": {
    "fs": false
  },
```
to package.json, alongside a `"process": "^0.11.10"` dependency, and
```
import * as process from "process/browser";

(window as any).process = process;
```
to `polyfills.ts`.

**Comment by billbarni** [comment]
I used this project as basis for a new one and it worked:
https://github.com/dariush-moshiri/antlr4ts-monaco-demo/

Why? I really don't know why... but the one I created using ng-cli does not compile for several reasons.
